"""Configuration layer — pydantic-settings backed."""

from .settings import (
    LLMSettings,
    Settings,
    SearchSettings,
    APISettings,
    AgentSettings,
    FalkorDBSettings,
    EmbeddingSettings,
    get_settings,
    reload_settings,
    get_minimax_api_key,
    get_minimax_base_url,
    get_minimax_model,
    get_deepseek_api_key,
    get_deepseek_base_url,
    get_deepseek_chat_model,
    get_deepseek_v4_model,
    get_kb_root,
    get_workspace_dir,
    get_llm_provider,
    get_generation_llm_provider,
    get_note_llm_provider,
    get_llm_timeout_sec,
    get_llm_reasoning_effort,
    get_api_cors_origins,
    get_agent_cards_dir,
    get_agent_recursion_limit,
    get_agent_memory_dir,
    require_secret,
    get_falkordb_settings,
    get_embedding_settings,
    get_falkordb_enabled,
)

__all__ = [
    "LLMSettings",
    "SearchSettings",
    "APISettings",
    "AgentSettings",
    "FalkorDBSettings",
    "EmbeddingSettings",
    "Settings",
    "get_settings",
    "reload_settings",
    "get_minimax_api_key",
    "get_minimax_base_url",
    "get_minimax_model",
    "get_deepseek_api_key",
    "get_deepseek_base_url",
    "get_deepseek_chat_model",
    "get_deepseek_v4_model",
    "get_kb_root",
    "get_workspace_dir",
    "get_llm_provider",
    "get_generation_llm_provider",
    "get_note_llm_provider",
    "get_llm_timeout_sec",
    "get_llm_reasoning_effort",
    "get_api_cors_origins",
    "get_agent_cards_dir",
    "get_agent_recursion_limit",
    "get_agent_memory_dir",
    "require_secret",
    "get_falkordb_settings",
    "get_embedding_settings",
    "get_falkordb_enabled",
]

__doc__ = "Configuration layer — pydantic-settings backed."
