/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAssociationDialog: typeof import('./src/components/AddAssociationDialog.vue')['default']
    AssociationsView: typeof import('./src/components/AssociationsView.vue')['default']
    AudioPreview: typeof import('./src/components/file-preview/AudioPreview.vue')['default']
    ChatPanel: typeof import('./src/components/ChatPanel.vue')['default']
    CsvPreview: typeof import('./src/components/file-preview/CsvPreview.vue')['default']
    DocxPreview: typeof import('./src/components/file-preview/DocxPreview.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    FilePreviewDialog: typeof import('./src/components/file-preview/FilePreviewDialog.vue')['default']
    GraphCanvas: typeof import('./src/components/GraphCanvas.vue')['default']
    HtmlPreview: typeof import('./src/components/file-preview/HtmlPreview.vue')['default']
    ImagePreview: typeof import('./src/components/file-preview/ImagePreview.vue')['default']
    MarkdownPreview: typeof import('./src/components/file-preview/MarkdownPreview.vue')['default']
    MemorySearchDialog: typeof import('./src/components/MemorySearchDialog.vue')['default']
    MermaidPreview: typeof import('./src/components/file-preview/MermaidPreview.vue')['default']
    MermaidViewer: typeof import('./src/components/MermaidViewer.vue')['default']
    NodeEditDialog: typeof import('./src/components/NodeEditDialog.vue')['default']
    NodeNotePanel: typeof import('./src/components/NodeNotePanel.vue')['default']
    OutlineView: typeof import('./src/components/OutlineView.vue')['default']
    PdfPreview: typeof import('./src/components/file-preview/PdfPreview.vue')['default']
    PlanActionContent: typeof import('./src/components/PlanActionContent.vue')['default']
    PlanDialog: typeof import('./src/components/PlanDialog.vue')['default']
    PptxPreview: typeof import('./src/components/file-preview/PptxPreview.vue')['default']
    ResourceDialog: typeof import('./src/components/ResourceDialog.vue')['default']
    TextPreview: typeof import('./src/components/file-preview/TextPreview.vue')['default']
    TimelinePanel: typeof import('./src/components/TimelinePanel.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UnsupportedPreview: typeof import('./src/components/file-preview/UnsupportedPreview.vue')['default']
    VideoPreview: typeof import('./src/components/file-preview/VideoPreview.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
